# Generated by Django 4.0.2 on 2022-03-10 21:13

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, default='Anonymous', max_length=14, verbose_name='Name')),
                ('body', models.CharField(blank=True, db_index=True, max_length=140, null=True, verbose_name='Body')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='Create DateTime')),
                ('image', cloudinary.models.CloudinaryField(blank=True, db_index=True, max_length=255, verbose_name='image')),
                ('likecount', models.IntegerField(blank=True, default=0, verbose_name='like_count')),
            ],
            options={
                'db_table': ' post',
            },
        ),
    ]
